### ISSUE TITLE
roll & yaw seems swapped

### ISSUE THREAD

**Issue by mnjm97** [3rl-io/spidgets-mobile#1]
no matter which way I hold the device it seems like it is rolling when I turn and turning when I roll.  toggling "roll off" does not stop it from rolling.

**Comment by kkota1** [comment]
Is this a Samsung phone? Currently it expects the screen facing up and top of the screen pointing forward

**Comment by kkota1** [comment]
And the browser in your AR glasses, not phone screen

**Comment by mnjm97** [comment]
ok, so I guess I never tried face up.  that seems to work as intended.
